proyectoWeb/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="blog"),    #no es necesario agregarle el primer argumento a path porque ya estamos en la carpeta raiz de la view
    path('categoria/<int:categoria_id>', views.categoria, name='categoria')
]

proyectoWeb/carro/urls.py
from django.urls import path
from . import views

app_name = "carro"    #nombre de espacio para utilizar todas las urls 

urlpatterns = [
    path('agregar/<int:producto_id>', views.agregarProducto, name="agregar"),
    path('eliminar/<int:producto_id>', views.eliminarProducto, name="eliminar"),
    path('restar/<int:producto_id>', views.restarProducto, name="restar"),
    path('limpiar/', views.limpiarCarro, name="limpiar"),
]

proyectoWeb/proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),  #enlazando urls de la app
    path('servicios/', include('servicio.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('login/', include('login.urls')),
    path('pedidos/', include('pedidos.urls')),
]

proyectoWeb/tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="tienda"),
]

proyectoWeb/carro/models.py
from django.db import models

# Create your models here.

proyectoWeb/tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50)
    creacion = models.DateTimeField(auto_now_add=True)
    actualizacion = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProductos'
        verbose_name_plural = 'categoriasProductos'
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    disponibilidad = models.BooleanField(default=True)
    categoria = models.ManyToManyField(CategoriaProducto)      #creando una relacion de tablas varios a varios con producto y CategoriaProducto
    creacion = models.DateTimeField(auto_now_add=True)
    actualizacion = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'produtco'
        verbose_name_plural = 'productos'
    
    def __str__(self):
        return self.nombre

proyectoWeb/carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from tienda.models import Producto

# Create your views here.

def agregarProducto(request, producto_id):
    carro = Carro(request)           #creando nuestro objeto Carro
    producto = Producto.objects.get(id=producto_id)  #buscamos el producto segun el id
    carro.agregar(producto=producto)

    return redirect("tienda")

def eliminarProducto(request, producto_id):
    carro = Carro(request)           
    producto = Producto.objects.get(id=producto_id)  
    carro.eliminar(producto=producto)

    return redirect("tienda")

def restarProducto(request, producto_id):
    carro = Carro(request)           
    producto = Producto.objects.get(id=producto_id) 
    carro.restarProducto(producto=producto)

    return redirect("tienda")

def limpiarCarro(request):
    carro = Carro(request)           
    carro.limpiarCarro()

    return redirect("tienda")

proyectoWeb/tienda/views.py
from django.shortcuts import render
from .models import Producto, CategoriaProducto

# Create your views here.

def tienda(request):

    productos = Producto.objects.all() 

    return render(request, "tienda/tienda.html", {'productos': productos})

proyectoWeb/tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}  <!-- agregando productos al carrito -->
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-succes" style="background-color: cornsilk; color: black;">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-succes" style="background-color: cornsilk; color: black;">-</a>
                        <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-succes" style="background-color: cornsilk; color: black;">Eliminar</a> <br>
                        ${{value.precio}}
                    </td>
                </tr>
            {% endfor %}
            
            
            
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: ${{importe_total_carro}}
            </td>
        </tr>
        {% if request.session.carro.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-sm btn-succes" style="background-color: cornsilk; color: black;">Comprar</a> &nbsp;&nbsp;
                    <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-succes" style="background-color: cornsilk; color: black;">Vaciar carro</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>

</table>